services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    # volumes:
    #   - ./mongo-seed:/app
    depends_on:
      - mongodb